### ISSUE TITLE
TS004F Switches

### ISSUE THREAD

**Issue by MattWestb** [MattWestb/tuya-Switches-Dimmer#1]
I have trying getting one gray and black ones from Spain but its looke they  is having problem shipping them and its not 100% its one TS004F iit can being TS0044 they is shipping.

Thanks in advance.

**Comment by MattWestb** [comment]
Hi  @smigima My Email mattwestb@gmail.com

**Comment by ghost** [comment]
Ok, I have  TS004F for sure as it was the desciption on ZHA page in HA.
I don't use it for now cause it is not working anyway, so I could send it
to you. I live in Poland so I don't know if it would be fast enough though
as I don't want to pay much money for shipping.

śr., 21 lip 2021 o 10:39 MattWestb ***@***.***> napisał(a):

**Comment by MattWestb** [comment]
I have ordering https://www.aliexpress.com/item/1005002181182397.html?spm=a2g0s.12269583.0.0.163858f1OHZkcY one gray and one black but its looks like the seller is not doing so much for getting it shipped :-((

Also tuya have 2 hardware versions one with one old zigbee module one one updated MG21 module that is very nice.

I hope i getting the updated version and can dumping the flash (if its not locked) so can using it for "converting" other TS004X switches. And if i getting one TS0044 and can dumping it then user can re flashing there switches if having the same hardware version.

And my optimal thing is cooking one double dimmer switch for the hardware (2 on/off Dim up/ down like IKEA On/Off switch is) one right and one left and also is possible one quad dimmer (toggle and dim up down with long pressing) but i is not so good on coding but i have the dev tools from Silabs.

**Comment by MattWestb** [comment]
Is your TS004F  one new version like the right on on the photo ?
![TUYA-Dimmer01](https://user-images.githubusercontent.com/49618193/127646222-480c943c-79f1-47bb-800f-f44260a2ad9e.jpeg)
![TUYA-Dimmer02](https://user-images.githubusercontent.com/49618193/127647040-5dd88ef8-0d0e-461f-8e97-3a1ea48889ca.jpeg)

If i getting one with the same hardware but one TS0044 i can trying dumping the flash and user data and then its possible "converting" TS004F to TS0044  if having one working SWD programmer but its only possible if tuya have not disabling the debug and protecting the module (LIDL LED strip and ZBGW was not).

My ordered switches is not being shipped from Poland ;-((

Its looks like the new version of the quirk is working OK with all we can getting from the dimmer switch for the moment but need the last OK before pushing it into dev branch.
